### ISSUE TITLE
It's laggy on iPhone

### ISSUE THREAD

**Issue by fransoudelaar** [geosigno/simpleParallax.js#47]
Please check it out on iPhone. It's really laggy. The examples on https://simpleparallax.com/ are laggy as well. 

Testet with:
iPhone XR
iOS: 13.4.1
Safari

**Comment by geosigno** [comment]
Issue has been fixed. Thanks!

**Comment by fransoudelaar** [comment]
Nice job. Do you release a new version?

**Comment by geosigno** [comment]
The issue was on the demo website itself, not the plugin.

**Comment by fransoudelaar** [comment]
The issue still occurs on the demo website as far as I can see on my iPhone. I am also encountered this issue on my implementation which is why I report it.

**Comment by fransoudelaar** [comment]
I captured a screen recording of the behaviour on my iPhone XR in Safari: https://we.tl/t-5pbKSatUgZ

**Comment by geosigno** [comment]
This is definitely not good! I'll try to reproduce on my side. Was it fixed at some point on the demo website on your phone?

**Comment by fransoudelaar** [comment]
Not that I know.

**Comment by geosigno** [comment]
I was able to reproduce it on an other iPhone 8 (exactly the same as mine...). I started to debug it and it seems the delay parameter - that will attach the CSS transition - is causing the issue. By default this delay is set at 0.4.

Could you please try to set that delay at 0, and check on your local if you are still facing the issue?

**Comment by P4KM4N** [comment]
I confirm that setting the delay parameter to 0 fix the issue! Thanks

**Comment by fransoudelaar** [comment]
A delay of 0.2 seems to fix the issue as well on my iPhone XR. 

My images got a `transition: all 0.3s ease` from my lazyloaded classname which was fading in the images. This was conflicting the parallax transition. I removed the transition of the lazyloaded style and changed the delay to 0.2. Works fine now.

**Comment by luchi222** [comment]
hi my iphone xr has screen stuttering problems, do you think this could solve it?

**Comment by geosigno** [comment]
The issue seems related to https://bugs.chromium.org/p/chromium/issues/detail?id=899130

**Comment by maroluke** [comment]
Same behavior solved with setting the delay. Awesome!

**Comment by geosigno** [comment]
This is fixed now in Chrome.
